// Textos editoriales predeterminados; el administrador puede personalizar cada campaña.
export const heroSlides = [
  {
    eyebrow: 'El arte de encontrar tu aroma',
    title: ['Una fragancia.', 'Muchas formas', 'de ser tú.'],
    description: 'Conoce marcas, notas y presentaciones antes de elegir.',
    cta: 'Explorar perfumes',
    to: '/tienda',
    image: 'hero-v2-lumiere',
    layout: 'left',
    tone: 'light',
    alt: 'Frasco de cristal sobre piedra blanca, bañado por luz natural',
  },
  {
    eyebrow: 'Una pausa para descubrir',
    title: ['Lo sutil también', 'deja huella.'],
    description: 'Notas verdes y maderas suaves para un momento de calma.',
    cta: 'Ver destacados',
    to: '/#destacados',
    image: 'hero-v2-silence',
    layout: 'right',
    tone: 'light',
    alt: 'Frasco verde sobre un bloque de vidrio entre reflejos de luz',
  },
  {
    eyebrow: 'La firma Forme',
    title: ['Tu esencia.', 'A tu manera.'],
    description: 'Flores suaves y composiciones para llevar cerca de la piel.',
    cta: 'Ver Forme',
    to: '/marcas/forme',
    image: 'hero-v3-petale',
    layout: 'left',
    tone: 'light',
    alt: 'Frasco rosado de Forme sobre piedra clara y seda blanca',
  },
  {
    eyebrow: 'Facetas cálidas',
    title: ['Ámbar y madera,', 'sin prisa.'],
    description: 'Especias suaves y resinas en composiciones envolventes.',
    cta: 'Explorar la tienda',
    to: '/tienda',
    image: 'hero-v4-amber',
    layout: 'left',
    tone: 'warm',
    alt: 'Frasco ámbar sin marca sobre piedra clara y madera oscura',
  },
  {
    eyebrow: 'Notas luminosas',
    title: ['La frescura', 'también tiene voz.'],
    description: 'Cítricos y acordes ligeros para los días de sol.',
    cta: 'Explorar la tienda',
    to: '/tienda',
    image: 'hero-v4-citrus',
    layout: 'right',
    tone: 'light',
    alt: 'Frasco claro sin marca junto a bergamota y piedra blanca',
  },
]

export const categories = [
  {
    id: 'hombre',
    title: 'Para él',
    description: 'Acordes amaderados y frescos.',
    to: '/tienda?genero=hombre',
    image: 'discovery-bois',
    layout: 'portrait',
    reveal: 'from-left',
    width: 1024,
    height: 1536,
  },
  {
    id: 'mujer',
    title: 'Para ella',
    description: 'Flores de distintos matices.',
    to: '/tienda?genero=mujer',
    image: 'discovery-petale',
    layout: 'landscape',
    reveal: 'from-right',
    width: 1536,
    height: 1024,
  },
  {
    id: 'unisex',
    title: 'Unisex',
    description: 'Perfiles para llevar como prefieras.',
    to: '/tienda?genero=unisex',
    image: 'discovery-libre',
    layout: 'panorama',
    reveal: 'from-right',
    width: 1536,
    height: 1024,
  },
]
